#!/bin/bash -e


function restore_saved_artifacts() {
  if [ "$(ls -A /tmp/artifacts/ 2>/dev/null)" ]; then
    echo  "Restoring saved artifacts from prior build..."
    mv /tmp/artifacts/.[!.]* $HOME/.
  fi
}

# Source code provided to S2I is at ${HOME}
if [[ "$1" == "-h" ]]; then
	exec /usr/libexec/s2i/usage
fi


LOCAL_SOURCE_DIR=/tmp/src

DEPLOY_DIR=$CATALINA_HOME/webapps/

restore_saved_artifacts

pushd $LOCAL_SOURCE_DIR &> /dev/null

cp -r resources/xml/ $HOME/.meditor/

mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=6.0p -DbuildDate=2017-01-11

mvn clean install --batch-mode -DskipTests

mv ./target/meditor.war $DEPLOY_DIR
unzip -o resources/djatoka/dist/djatoka.war -d $CATALINA_HOME/webapps/djatoka
cp resources/djatoka/bin/log4j.properties $CATALINA_HOME/webapps/djatoka/WEB-INF/classes/log4j.properties
cp resources/djatoka/dist/djatoka.properties $CATALINA_HOME/webapps/djatoka/WEB-INF/classes/djatoka.properties
chmod -R go+w $CATALINA_HOME/webapps/djatoka/WEB-INF/classes

mv resources/djatoka/ $HOME/.meditor/
mv $HOME/lib/libyaz4j.so $LD_LIBRARY_PATH/
mv resources/convertAudio/ $HOME/.meditor/

